### ISSUE TITLE
CHILD-P1-R01-02 future-date apply 失敗と retry の PoC シナリオを実装する

### ISSUE THREAD

**Issue by TommyKammy** [TommyKammy/HRCore#150]
## Summary

Implement a synthetic future-date apply failure and retry PoC that proves scheduled lifecycle work can leave durable failure evidence and be retried without double-applying HR Core state.

## Scope

- add a local synthetic job/apply entrypoint or test fixture for future-date lifecycle application
- simulate at least one deterministic apply failure after preconditions are checked
- persist or expose enough failure evidence for an operator-facing retry decision at PoC depth
- prove retry succeeds or remains held without duplicating person / employment / assignment / lifecycle_event / audit_event effects
- align retry correlation with the idempotency behavior introduced by #149
- keep this local-only and synthetic; do not add production scheduler, queue, worker fleet, DLQ, or cloud infrastructure

Part of: #148
Depends on: #149
Parallelizable: No

## Execution order

2 of 4

## Acceptance criteria

- tests cover a deterministic future-date apply failure path
- tests cover a retry path that does not double-apply lifecycle state or audit evidence
- failure evidence includes stable IDs, correlation ID, failure reason, retryability, and observed state sufficient for the next traceability child issue
- invalid or stale retry attempts fail closed without partial durable writes
- no production scheduling, AWS, queue, DLQ, real employee data, or real provider calls are introduced

## Negative tests

- this issue does not implement a production background worker or scheduler
- this issue does not claim operational alerting, on-call, RTO/RPO, or DLQ readiness
- this issue does not broaden legal/privacy/two-key ADR status beyond existing Proposed anchors

## Verification

- npm run verify:pre-pr
